### ISSUE TITLE
UI not working with registry

### ISSUE THREAD

**Issue by jorgegilmoreira** [kwk/docker-registry-frontend#20]
Iḿ using this registry from https://github.com/docker/docker-registry#search-engine-options and the ui is not working.
The ui does not list any docker images and gives the error as below (using inspect from browser):

``` javascript
 GET http://148.251.162.83:8080/v1/search?q= 503 (Service Unavailable)vendor.3e65ee33.js:5 (anonymous function)vendor.3e65ee33.js:4 vvendor.3e65ee33.js:4 jvendor.3e65ee33.js:5 ivendor.3e65ee33.js:5 (anonymous function)vendor.3e65ee33.js:5 l.$evalvendor.3e65ee33.js:5 l.$digestvendor.3e65ee33.js:5 l.$applyvendor.3e65ee33.js:4 fvendor.3e65ee33.js:4 rvendor.3e65ee33.js:4 v.onload
vendor.3e65ee33.js:5 SyntaxError: Unexpected token <
    at Object.parse (native)
    at Object.S [as fromJson] (http://148.251.162.83:8080/scripts/vendor.3e65ee33.js:3:24638)
    at a.query.transformResponse (http://148.251.162.83:8080/scripts/scripts.1383ebe4.js:1:7816)
    at ic (http://148.251.162.83:8080/scripts/vendor.3e65ee33.js:4:27334)
    at e (http://148.251.162.83:8080/scripts/vendor.3e65ee33.js:4:27952)
    at i (http://148.251.162.83:8080/scripts/vendor.3e65ee33.js:5:13781)
    at http://148.251.162.83:8080/scripts/vendor.3e65ee33.js:5:13953
    at l.$eval (http://148.251.162.83:8080/scripts/vendor.3e65ee33.js:5:21080)
    at l.$digest (http://148.251.162.83:8080/scripts/vendor.3e65ee33.js:5:19589)
    at l.$apply (http://148.251.162.83:8080/scripts/vendor.3e65ee33.js:5:21347)vendor.3e65ee33.js:5 (anonymous function)vendor.3e65ee33.js:4 (anonymous function)vendor.3e65ee33.js:5 ivendor.3e65ee33.js:5 (anonymous function)vendor.3e65ee33.js:5 l.$evalvendor.3e65ee33.js:5 l.$digestvendor.3e65ee33.js:5 l.$applyvendor.3e65ee33.js:4 fvendor.3e65ee33.js:4 rvendor.3e65ee33.js:4 v.onload
vendor.3e65ee33.js:5 TypeError: Cannot read property 'ignoreLoadingBar' of undefined
    at responseError (http://148.251.162.83:8080/scripts/vendor.3e65ee33.js:11:27140)
    at i (http://148.251.162.83:8080/scripts/vendor.3e65ee33.js:5:13781)
    at http://148.251.162.83:8080/scripts/vendor.3e65ee33.js:5:13953
    at l.$eval (http://148.251.162.83:8080/scripts/vendor.3e65ee33.js:5:21080)
    at l.$digest (http://148.251.162.83:8080/scripts/vendor.3e65ee33.js:5:19589)
    at l.$apply (http://148.251.162.83:8080/scripts/vendor.3e65ee33.js:5:21347)
    at f (http://148.251.162.83:8080/scripts/vendor.3e65ee33.js:4:29534)
    at r (http://148.251.162.83:8080/scripts/vendor.3e65ee33.js:4:31397)
    at XMLHttpRequest.v.onload (http://148.251.162.83:8080/scripts/vendor.3e65ee33.js:4:31937)
vendor.3e65ee33.js:5 GET http://148.251.162.83:8080/v1/search?q= 503 (Service Unavailable)
vendor.3e65ee33.js:5 SyntaxError: Unexpected token <
    at Object.parse (native)
    at Object.S [as fromJson] (http://148.251.162.83:8080/scripts/vendor.3e65ee33.js:3:24638)
    at a.query.transformResponse (http://148.251.162.83:8080/scripts/scripts.1383ebe4.js:1:7816)
    at ic (http://148.251.162.83:8080/scripts/vendor.3e65ee33.js:4:27334)
    at e (http://148.251.162.83:8080/scripts/vendor.3e65ee33.js:4:27952)
    at i (http://148.251.162.83:8080/scripts/vendor.3e65ee33.js:5:13781)
    at http://148.251.162.83:8080/scripts/vendor.3e65ee33.js:5:13953
    at l.$eval (http://148.251.162.83:8080/scripts/vendor.3e65ee33.js:5:21080)
    at l.$digest (http://148.251.162.83:8080/scripts/vendor.3e65ee33.js:5:19589)
    at l.$apply (http://148.251.162.83:8080/scripts/vendor.3e65ee33.js:5:21347)vendor.3e65ee33.js:5 (anonymous function)vendor.3e65ee33.js:4 (anonymous function)vendor.3e65ee33.js:5 ivendor.3e65ee33.js:5 (anonymous function)vendor.3e65ee33.js:5 l.$evalvendor.3e65ee33.js:5 l.$digestvendor.3e65ee33.js:5 l.$applyvendor.3e65ee33.js:4 fvendor.3e65ee33.js:4 rvendor.3e65ee33.js:4 v.onload
vendor.3e65ee33.js:5 TypeError: Cannot read property 'ignoreLoadingBar' of undefined
    at responseError (http://148.251.162.83:8080/scripts/vendor.3e65ee33.js:11:27140)
    at i (http://148.251.162.83:8080/scripts/vendor.3e65ee33.js:5:13781)
    at http://148.251.162.83:8080/scripts/vendor.3e65ee33.js:5:13953
    at l.$eval (http://148.251.162.83:8080/scripts/vendor.3e65ee33.js:5:21080)
    at l.$digest (http://148.251.162.83:8080/scripts/vendor.3e65ee33.js:5:19589)
    at l.$apply (http://148.251.162.83:8080/scripts/vendor.3e65ee33.js:5:21347)
    at f (http://148.251.162.83:8080/scripts/vendor.3e65ee33.js:4:29534)
    at r (http://148.251.162.83:8080/scripts/vendor.3e65ee33.js:4:31397)
    at XMLHttpRequest.v.onload (http://148.251.162.83:8080/scripts/vendor.3e65ee33.js:4:31937)
```

**Comment by kwk** [comment]
Hi @jorgegilmoreira. Is the registry itself (not the frontend) working correctly?

Can you ping the registry? (`curl your-registry.host` should yield `true`)

How did you start the docker-registry-frontend? Please specify all arguments. If you're running from the docker Hub images, please do a `docker pull  konradkleine/docker-registry-frontend` to get the latest version.

**Comment by jorgegilmoreira** [comment]
Hi,
Thanks for your reply!
Yes i can assume registry is working fine, the curl works.
I made it available to you on docker.movves.io
I started your container like this: 
sudo docker run -d -e ENV_DOCKER_REGISTRY_HOST=localhost -e ENV_DOCKER_REGISTRY_PORT=5000 -p 8080:80 konradkleine/docker-registry-frontend
Thanks in advance!


Best Regards,
Jorge Moreira

**Comment by kwk** [comment]
Any updates on this issue?

**Comment by jgangemi** [comment]
how are you starting the registry itself? i had a problem like this yesterday and realized it was b/c our container was started using the `local` flavor which does not cause sqlalchemy to load. overriding that as part of my config fixed the issue.

**Comment by dotneet** [comment]
I had similar problem.
In my case, this probelem was related to reverse-proxy.

I changed to use sub-domain instead of sub-directory.

http://example.com/docker-frontend/

to 

http://docker-frontend.example.com/

**Comment by sandric** [comment]
well, I don't know if thats the issue, maybe the thing is in `ENV_DOCKER_REGISTRY_HOST=localhost` ? localhost does not means localhost of host, where you run your container, but container's ip set up by docker. I had no repo's in UI while, they was there in registry, when I used the same run command as you. After setting full ip name of host machine, it started to work.

**Comment by hbokh** [comment]
I had the same issue.
Installed this container on localhost, pointing to a registry in the LAN. Not working...
Turned out I had no `SEARCH_BACKEND` enabled in the registry-container.
Here's my `docker-compose.yml` that is working:
```
registryRedis:
  image: redis:latest
privateReg:
  image: my_registry:latest
  environment:
    - SMTP_HOST=smtp.example.com
    - SMTP_PORT=587
    - SEARCH_BACKEND=sqlalchemy
  links:
    - registryRedis:redis
  volumes:
    - /registry-data:/data
  ports:
    - "5000:5000"
```
Hope this helps!

**Comment by kernelmode** [comment]
I have this issue too. Both registry and ui are started at vm-docker host.
http://vm-docker:5000/v1/search works and gives me list of my containers.
http://vm-docker:8080/#/repositories sends request to http://vm-docker:**8080**/v1/search, notice that the port is 8080 instead of 5000. I have supplied ENV_DOCKER_REGISTRY_PORT=5000 parameter, and `registry-host.json` file in the container has the following contents:
```
root@44613d1b31a0:/# cat /var/www/html/registry-host.json 
{"host": "localhost", "port": 5000}
``` 

It seems that port property is not being fetched properly.

**Comment by kwk** [comment]
@kernelmode It is totally fine for the container to fetch `http://vm-docker:8080/v1/search` instead of `http://vm-docker:5000/v1/search`. The `/v1/` will be proxied to your registry host. One cannot simply deliver a website with javascript (the docker-registry-frontent) to your browser and request content from another website (the docker registry) as this would require cross-origin-requests. One can configure the docker registry to allow cross origin requests but I didn't want to require a special configuration of the registry. Here you can see how the proxy is configured:

https://github.com/kwk/docker-registry-frontend/blob/master/apache-site.conf#L29

**Comment by kernelmode** [comment]
@kwk thanks, the issue was resolved by setting correct `--link registry_container_name`

**Comment by AngryHacker** [comment]
Hello, I had the same issue.

I run this command:
sudo docker run -d -e ENV_DOCKER_REGISTRY_HOST=localhost  
-e ENV_DOCKER_REGISTRY_PORT=5000 -p 8088:80 
 --link v1:registry --name frontend konradkleine/docker-registry-frontend

"v1" is my registry container name.
It raised 503 for "http://localhost:8088/v1/search?q=", but the "http://localhost:5000/v1/search" work well.

What's the problem may be?
Thank you!

**Comment by kwk** [comment]
@AngryHacker. Thank you for reporting your issue. Both `localhost` and `127.0.0.1` from the perspective of the frontend container resolve to the frontend container itself. It looks like you want to point the frontend to the host running the registry backend container. Therefore, try not using `localhost` instead use either a link name (if you started the frontend with a link to the registry container) or an IP (if possible **not** `127.0.0.1`).

Out of my memory, this should do the trick.

**docker-compose.yml**
```yml
frontend:
    image: frontend konradkleine/docker-registry-frontend
    ports:
         - "8088:80"
    links:
        - NAME_OF_REGISTRY_CONTAINER:registry
    environment:
        - ENV_DOCKER_REGISTRY_HOST=registry
        - ENV_DOCKER_REGISTRY_PORT=5000
```

Then run:

```
$ docker-compose up
```

**Comment by AngryHacker** [comment]
Thanks for your replay. I use the configuration below:
```yml
frontend:
    image: konradkleine/docker-registry-frontend
    ports:
         - "8088:80"
    links:
        - v1:registry
    environment:
        - ENV_DOCKER_REGISTRY_HOST=registry
        - ENV_DOCKER_REGISTRY_PORT=5000
v1:
    image: registry-v1
    volumes: 
        - /tmp/registry:/tmp/registry
    ports:
        - "5000:5000"
```
And it work fine. Thanks.

**Comment by kwk** [comment]
@AngryHacker That is good news!
