### ISSUE TITLE
when using s3 backend browse repositories home page show no repositories

### ISSUE THREAD

**Issue by maneeshmp** [kwk/docker-registry-frontend#71]
Registry setup command:

```
docker run -d \
-p 5000:5000 \
-e "REGISTRY_STORAGE=s3" \
-e "REGISTRY_STORAGE_S3_REGION=us-east-1" \
-e "REGISTRY_STORAGE_S3_BUCKET=test-registry" \
-e "REGISTRY_STORAGE_S3_ACCESSKEY=ASDFASDFASD" \
-e "REGISTRY_STORAGE_S3_SECRETKEY=ASDFASDFASDFASDFASD"  \
--name docker-registry-s3 \
registry:2.2.0
```

Registry proxy setup command:

```
docker run -d \
-p 443:443 \
-e REGISTRY_HOST="docker-registry-s3" \
-e REGISTRY_PORT="5000" \
-e SERVER_NAME="localhost" \
--link docker-registry-s3:docker-registry \
-v $PATH/registry.htpasswd:/etc/nginx/.htpasswd:ro \
-v $PATH/secure:/etc/nginx/ssl:ro \
--name registry-secure-s3 \
containersol/docker-registry-proxy
```

docker-registry-frontend setup command:

```
sudo docker run  -d  \
-e ENV_DOCKER_REGISTRY_HOST=docker-registry-s3 \
-e ENV_DOCKER_REGISTRY_PORT=5000  \
-p 8080:80 \
--name docker-ui  \
konradkleine/docker-registry-frontend:v2
```

but the ui doesn't show any repositories. Any clue?

If I ran docker-registry-frontend in detached mode, I get the below logs

```
Module auth_kerb disabled.
To activate the new configuration, you need to run:
  service apache2 restart
Module ssl already disabled
Enabling module rewrite.
To activate the new configuration, you need to run:
  service apache2 restart
Stopping web server: apache2.
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 10.0.0.4. Set the 'ServerName' directive globally to suppress this message
```

If I run in interactive mode to restart apache I get the below errors

```
service apache2 restart
[FAIL] Restarting web server: apache2 failed!
[warn] The apache2 configtest failed. ... (warning).
Output of config test was:
[Sat Nov 14 03:43:36.275005 2015] [core:warn] [pid 22:tid 140622179514240] AH00111: Config variable ${DOCKER_REGISTRY_SCHEME} is not defined
[Sat Nov 14 03:43:36.275100 2015] [core:warn] [pid 22:tid 140622179514240] AH00111: Config variable ${DOCKER_REGISTRY_HOST} is not defined
[Sat Nov 14 03:43:36.275105 2015] [core:warn] [pid 22:tid 140622179514240] AH00111: Config variable ${DOCKER_REGISTRY_PORT} is not defined
[Sat Nov 14 03:43:36.275110 2015] [core:warn] [pid 22:tid 140622179514240] AH00111: Config variable ${DOCKER_REGISTRY_SCHEME} is not defined
[Sat Nov 14 03:43:36.275114 2015] [core:warn] [pid 22:tid 140622179514240] AH00111: Config variable ${DOCKER_REGISTRY_HOST} is not defined
[Sat Nov 14 03:43:36.275117 2015] [core:warn] [pid 22:tid 140622179514240] AH00111: Config variable ${DOCKER_REGISTRY_PORT} is not defined
[Sat Nov 14 03:43:36.275134 2015] [core:warn] [pid 22:tid 140622179514240] AH00111: Config variable ${AUTH_NAME} is not defined
[Sat Nov 14 03:43:36.275143 2015] [core:warn] [pid 22:tid 140622179514240] AH00111: Config variable ${AUTH_KRB_REALMS} is not defined
[Sat Nov 14 03:43:36.275149 2015] [core:warn] [pid 22:tid 140622179514240] AH00111: Config variable ${AUTH_KRB_SERVICE_NAME} is not defined
[Sat Nov 14 03:43:36.275154 2015] [core:warn] [pid 22:tid 140622179514240] AH00111: Config variable ${AUTH_KRB5_KEYTAB} is not defined
AH00526: Syntax error on line 8 of /etc/apache2/sites-enabled/docker-site.conf:
Invalid command 'RewriteEngine', perhaps misspelled or defined by a module not included in the server configuration
Action 'configtest' failed.
The Apache error log may have more information.
```

Chrome console log shows 

```
Failed to load resource: the server responded with a status of 502 (Proxy Error)
vendor.9d7c0c79.js:5 SyntaxError: Unexpected token <
    at Object.parse (native)
    at Object.S [as fromJson] (http://test-registry.com:8080/scripts/vendor.9d7c0c79.js:3:24907)
    at a.query.transformResponse (http://test-registry.com:8080/scripts/scripts.e2fe09fb.js:1:10929)
    at ib (http://test-registry.com:8080/scripts/vendor.9d7c0c79.js:4:27864)
    at e (http://test-registry.com:8080/scripts/vendor.9d7c0c79.js:4:28482)
    at i (http://test-registry.com:8080/scripts/vendor.9d7c0c79.js:5:14638)
    at http://test-registry.com:8080/scripts/vendor.9d7c0c79.js:5:14810
    at n.$eval (http://test-registry.com:8080/scripts/vendor.9d7c0c79.js:5:22202)
    at n.$digest (http://test-registry.com:8080/scripts/vendor.9d7c0c79.js:5:20711)
    at n.$apply (http://test-registry.com:8080/scripts/vendor.9d7c0c79.js:5:22469)(anonymous function) @ vendor.9d7c0c79.js:5
vendor.9d7c0c79.js:5 TypeError: Cannot read property 'ignoreLoadingBar' of undefined
    at responseError (vendor.9d7c0c79.js:12)
    at i (vendor.9d7c0c79.js:5)
    at vendor.9d7c0c79.js:5
    at n.$eval (vendor.9d7c0c79.js:5)
    at n.$digest (vendor.9d7c0c79.js:5)
    at n.$apply (vendor.9d7c0c79.js:5)
    at f (vendor.9d7c0c79.js:4)
    at r (vendor.9d7c0c79.js:4)
    at XMLHttpRequest.v.onload (vendor.9d7c0c79.js:5)(anonymous function) @ vendor.9d7c0c79.js:5
```

**Comment by kwk** [comment]
I'm sorry, I cannot test against S3. I don't have an account.

**Comment by maneeshmp** [comment]
please send a mail to me, amazon will let us create a free account with s3 for 1 yr

**Comment by maneeshmp** [comment]
anyway looking at the error in the logs, do you have any clude?

**Comment by ghost** [comment]
The application works for me when using S3.

Example docker-compose.yml

```
---
registry:
  container_name: registry
  image: registry:2.2.0
  environment:
    - REGISTRY_HTTP_SECRET=XXX
    - REGISTRY_STORAGE=s3
    - REGISTRY_STORAGE_S3_REGION=XXX
    - REGISTRY_STORAGE_S3_BUCKET=XXX

docker-registry-frontend:
  container_name: docker-registry-frontend
  image: konradkleine/docker-registry-frontend:v2
  links:
    - registry
  environment:
    - ENV_DOCKER_REGISTRY_HOST=registry
    - ENV_DOCKER_REGISTRY_PORT=5000
```

**Comment by kwk** [comment]
@JBodkin Thank you for reporting this.

@maneeshmp Sorry that I cannot give you more support but please take a look at this [example setup](https://github.com/kwk/docker-registry-frontend/tree/v2/example-setup) and modify it to your needs. I cannot support all setups and in particular I won't support any proxy in between like you seem to have configured one.

**Comment by schmunk42** [comment]
@JBodkin Thank you for the example, I can confirm this is working.

It just takes forever to get a list from S3 :) `http.response.duration=1m10.962855092s` - I need to configure a redis cache or similar.
